#!/bin/bash -e
#
# This script is executed at the end of appliance creation.  Here you can do
# one-time actions to modify your appliance before it is ever used, like
# removing files and directories to make it smaller, creating symlinks,
# generating indexes, etc.
#
# The 'kiwi_type' variable will contain the format of the appliance
# (oem = disk image, vmx = VMware, iso = CD/DVD, xen = Xen).
#

# read in some variables
. /studio/profile

# read in KIWI utility functions
. /.kconfig

# create transmart tablespaces
mkdir /opt/transmart/
mkdir /opt/transmart/db
mkdir /opt/transmart/db/biomart
mkdir /opt/transmart/db/deapp
mkdir /opt/transmart/db/indx
mkdir /opt/transmart/db/search_app
mkdir /opt/transmart/db/transmart
chown postgres.postgres /opt/transmart/db/*
R CMD BATCH /tmp/install-r-packages.r /tmp/install-r-packages.log
chkconfig --set tomcat on
chkconfig --set postgresql on
chkconfig --set transmart-components on
chkconfig --set apache2 on